services:
    laravel.test:
        container_name: sisgape
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
            - 'sisgape.test:127.0.0.1'
        ports:
            - "8686:8080"
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql-sisgape
            - sqlserver-sisgape

    mysql-sisgape:
        image: 'mysql/mysql-server:8.0'
        container_name: sisgape-mysql
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'MinisterioMgi*Passw12'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'sisgape'
            MYSQL_USER: 'sisgape'
            MYSQL_PASSWORD: 'MinisterioMgi*Passw12'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    sqlserver-sisgape:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - '11433:1433'
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'MgI*pAss*1103'
            MSSQL_PID: 'Developer'
        volumes:
            - sail-mssql:/var/opt/mssql
        networks:
            - sail
networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-mssql:
        driver: local
